version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_SERVER
  build:
    commands:
      - export GIT_TAG=${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/}
      - export IMAGE_URI=${IMAGE_URI_BASE}:${GIT_TAG}

      - echo Building Docker image as ${IMAGE_URI}...
      - docker build -t ${IMAGE_URI} lambdas/code_exec

      - echo Pushing Docker image...
      - docker push ${IMAGE_URI}

      - cd lambdas/slack_listener
      - go mod download
      - GOOS=linux go build -o slack_listener *.go
      - cd ../../
      - mv lambdas/run/slack_listener ./

      - cd lambdas/slack_responder
      - go mod download
      - GOOS=linux go build -o slack_responder *.go
      - cd ../../
      - mv lambdas/run/slack_responder ./

      - aws cloudformation package --template-file template.yml --s3-bucket "resl-build-artifacts" --output-template-file outputtemplate.yml

      - echo Deploying project...
      - |
        aws cloudformation deploy \
          --stack-name $PROJECT_NAME \
          --template-file outputtemplate.yml \
          --parameter-overrides ImageUri=${IMAGE_URI} \
          --capabilities CAPABILITY_IAM
